/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define PERIPH_BASE        (0x40000000UL)
#define APB1PERIPH_BASE    PERIPH_BASE
#define APB2PERIPH_BASE    (PERIPH_BASE + 0x10000UL)
#define AHBPERIPH_BASE     (PERIPH_BASE + 0x20000UL)

#define RCC_BASE           (AHBPERIPH_BASE + 0x1000UL)
#define GPIOA_BASE         (APB2PERIPH_BASE + 0x0800UL)
#define GPIOC_BASE         (APB2PERIPH_BASE + 0x1000UL)
#define USART2_BASE        (APB1PERIPH_BASE + 0x4400UL)
#define SYSTICK_BASE       (0xE000E010UL)

#define REG32(addr)        (*(volatile uint32_t *)(addr))

#define RCC_APB2ENR        REG32(RCC_BASE + 0x18UL)
#define RCC_APB1ENR        REG32(RCC_BASE + 0x1CUL)

#define GPIOA_CRL          REG32(GPIOA_BASE + 0x00UL)
#define GPIOC_CRH          REG32(GPIOC_BASE + 0x04UL)
#define GPIOC_IDR          REG32(GPIOC_BASE + 0x08UL)
#define GPIOC_ODR          REG32(GPIOC_BASE + 0x0CUL)

#define USART2_SR          REG32(USART2_BASE + 0x00UL)
#define USART2_DR          REG32(USART2_BASE + 0x04UL)
#define USART2_BRR         REG32(USART2_BASE + 0x08UL)
#define USART2_CR1         REG32(USART2_BASE + 0x0CUL)

#define SYSTICK_CSR        REG32(SYSTICK_BASE + 0x00UL)
#define SYSTICK_RVR        REG32(SYSTICK_BASE + 0x04UL)
#define SYSTICK_CVR        REG32(SYSTICK_BASE + 0x08UL)

#define RCC_APB2ENR_AFIOEN (1UL << 0)
#define RCC_APB2ENR_IOPAEN (1UL << 2)
#define RCC_APB2ENR_IOPCEN (1UL << 4)
#define RCC_APB1ENR_USART2EN (1UL << 17)

#define USART_SR_TXE       (1UL << 7)
#define USART_CR1_TE       (1UL << 3)
#define USART_CR1_UE       (1UL << 13)

#define SYSTICK_CSR_ENABLE    (1UL << 0)
#define SYSTICK_CSR_CLKSOURCE (1UL << 2)
#define SYSTICK_CSR_COUNTFLAG (1UL << 16)

#define USER_BUTTON_PIN    (13UL)
#define USER_BUTTON_MASK   (1UL << USER_BUTTON_PIN)
#define SUCCESS_MIN_MS     (4900UL)
#define SUCCESS_MAX_MS     (6000UL)

static uint32_t system_millis = 0UL;

void SystemInit(void)
{
}

static void systick_init(void)
{
    SYSTICK_RVR = 8000UL - 1UL; /* 1 ms tick from the default 8 MHz HSI clock. */
    SYSTICK_CVR = 0UL;
    SYSTICK_CSR = SYSTICK_CSR_CLKSOURCE | SYSTICK_CSR_ENABLE;
}

static void delay_ms(uint32_t milliseconds)
{
    while (milliseconds-- != 0UL) {
        while ((SYSTICK_CSR & SYSTICK_CSR_COUNTFLAG) == 0UL) {
        }
        system_millis++;
    }
}

static uint32_t millis(void)
{
    return system_millis;
}

static void uart2_init(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_AFIOEN | RCC_APB2ENR_IOPAEN;
    RCC_APB1ENR |= RCC_APB1ENR_USART2EN;

    /* PA2: USART2_TX, alternate-function push-pull, 50 MHz. */
    GPIOA_CRL &= ~(0xFUL << (2UL * 4UL));
    GPIOA_CRL |=  (0xBUL << (2UL * 4UL));

    USART2_BRR = 0x0341UL; /* 8 MHz APB1 clock / 9600 baud. */
    USART2_CR1 = USART_CR1_TE | USART_CR1_UE;
}

static void user_button_init(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_IOPCEN;

    /* PC13: input with pull-up. Nucleo USER button reads low when pressed. */
    GPIOC_CRH &= ~(0xFUL << ((USER_BUTTON_PIN - 8UL) * 4UL));
    GPIOC_CRH |=  (0x8UL << ((USER_BUTTON_PIN - 8UL) * 4UL));
    GPIOC_ODR |= USER_BUTTON_MASK;
}

static uint32_t user_button_is_pressed(void)
{
    return (GPIOC_IDR & USER_BUTTON_MASK) == 0UL;
}

static void uart2_write_char(char ch)
{
    while ((USART2_SR & USART_SR_TXE) == 0UL) {
    }

    USART2_DR = (uint32_t)ch;
}

static void uart2_write_string(const char *text)
{
    while (*text != '\0') {
        uart2_write_char(*text++);
    }
}

static void uart2_write_uint(uint32_t value)
{
    char digits[10];
    uint32_t index = 0UL;

    if (value == 0UL) {
        uart2_write_char('0');
        return;
    }

    while (value != 0UL) {
        digits[index++] = (char)('0' + (value % 10UL));
        value /= 10UL;
    }

    while (index != 0UL) {
        uart2_write_char(digits[--index]);
    }
}

int main(void)
{
    uint32_t button_was_pressed = 0UL;
    uint32_t press_start_ms = 0UL;

    systick_init();
    uart2_init();
    user_button_init();

    for (;;) {
        const uint32_t now_ms = millis();
        const uint32_t button_is_pressed = user_button_is_pressed();

        if ((button_is_pressed != 0UL) && (button_was_pressed == 0UL)) {
            press_start_ms = now_ms;
            uart2_write_string("START\r\n");
        }

        if ((button_is_pressed == 0UL) && (button_was_pressed != 0UL)) {
            const uint32_t pressed_time_ms = now_ms - press_start_ms;

            uart2_write_string("duration=");
            uart2_write_uint(pressed_time_ms);
            uart2_write_string(" ms, ");

            if ((pressed_time_ms > SUCCESS_MIN_MS) && (pressed_time_ms < SUCCESS_MAX_MS)) {
                uart2_write_string("SUCCESS\r\n");
            } else {
                uart2_write_string("FAIL\r\n");
            }
        }

        button_was_pressed = button_is_pressed;
        delay_ms(1UL);
    }
}
