/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE                (0x40021000UL)
#define GPIOA_BASE              (0x40010800UL)

#define RCC_APB2ENR             (*(volatile uint32_t *)(RCC_BASE + 0x18UL))

#define GPIOA_CRL               (*(volatile uint32_t *)(GPIOA_BASE + 0x00UL))
#define GPIOA_BSRR              (*(volatile uint32_t *)(GPIOA_BASE + 0x10UL))

#define SYST_CSR                (*(volatile uint32_t *)0xE000E010UL)
#define SYST_RVR                (*(volatile uint32_t *)0xE000E014UL)
#define SYST_CVR                (*(volatile uint32_t *)0xE000E018UL)

#define RCC_APB2ENR_IOPAEN      (1UL << 2)
#define LED_PIN                 (1UL << 5)   /* NUCLEO-F103RB LD2: PA5 */
#define SYSTEM_CLOCK_HZ         (8000000UL)  /* Reset clock: HSI 8 MHz */
#define SYSTICK_RELOAD_1MS      ((SYSTEM_CLOCK_HZ / 1000UL) - 1UL)
#define LED_ON_TIME_MS          (500UL)
#define LED_SLOW_PERIOD_MS      (5000UL)
#define LED_FAST_PERIOD_MS      (2000UL)

void SystemInit(void)
{
    /* Keep the reset clock configuration: HSI 8 MHz. */
}

static void gpio_init(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_IOPAEN;

    /* PA5: general-purpose push-pull output, max speed 2 MHz. */
    GPIOA_CRL &= ~(0xFUL << 20);
    GPIOA_CRL |=  (0x2UL << 20);
}

static void systick_init(void)
{
    SYST_RVR = SYSTICK_RELOAD_1MS;
    SYST_CVR = 0UL;
    SYST_CSR = (1UL << 2) | (1UL << 0);
}

static void delay_ms(uint32_t ms)
{
    while (ms-- > 0UL)
    {
        while ((SYST_CSR & (1UL << 16)) == 0UL)
        {
        }
    }
}

static void blink_led_once(uint32_t period_ms)
{
    GPIOA_BSRR = LED_PIN;
    delay_ms(LED_ON_TIME_MS);
    GPIOA_BSRR = LED_PIN << 16;
    delay_ms(period_ms - LED_ON_TIME_MS);
}

int main(void)
{
    gpio_init();
    systick_init();

    for (;;)
    {
        blink_led_once(LED_SLOW_PERIOD_MS);
        blink_led_once(LED_FAST_PERIOD_MS);
    }
}
