/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define REG32(address) (*(volatile uint32_t *)(address))

#define RCC_BASE         0x40021000UL
#define RCC_APB2ENR      REG32(RCC_BASE + 0x18UL)
#define RCC_APB2ENR_IOPCEN (1UL << 4)

#define GPIOC_BASE       0x40011000UL
#define GPIOC_CRH        REG32(GPIOC_BASE + 0x04UL)
#define GPIOC_BSRR       REG32(GPIOC_BASE + 0x10UL)

#define CORE_DEBUG_DEMCR REG32(0xE000EDFCUL)
#define DWT_CTRL         REG32(0xE0001000UL)
#define DWT_CYCCNT       REG32(0xE0001004UL)

#define CORE_DEBUG_DEMCR_TRCENA (1UL << 24)
#define DWT_CTRL_CYCCNTENA      (1UL << 0)

#define SYS_CLOCK_HZ     8000000UL
#define SINE_PIN         8UL
#define SINE_PIN_MASK    (1UL << SINE_PIN)

#define PWM_PERIOD_US    100UL
#define SINE_HOLD_CYCLES 2U

void SystemInit(void)
{
    /* Keep the reset default HSI clock: SYSCLK = 8 MHz. */
}

static const uint8_t sine_duty_percent[] = {
    50, 55, 60, 65, 69, 74, 78, 82,
    85, 88, 91, 94, 96, 98, 99, 100,
    100, 100, 99, 98, 96, 94, 91, 88,
    85, 82, 78, 74, 69, 65, 60, 55,
    50, 45, 40, 35, 31, 26, 22, 18,
    15, 12, 9, 6, 4, 2, 1, 0,
    0, 0, 1, 2, 4, 6, 9, 12,
    15, 18, 22, 26, 31, 35, 40, 45
};

static void cycle_counter_init(void)
{
    CORE_DEBUG_DEMCR |= CORE_DEBUG_DEMCR_TRCENA;
    DWT_CYCCNT = 0U;
    DWT_CTRL |= DWT_CTRL_CYCCNTENA;
}

static void delay_us(uint32_t us)
{
    const uint32_t start = DWT_CYCCNT;
    const uint32_t cycles = (SYS_CLOCK_HZ / 1000000UL) * us;

    while ((uint32_t)(DWT_CYCCNT - start) < cycles) {
    }
}

static void sine_pin_high(void)
{
    GPIOC_BSRR = SINE_PIN_MASK;
}

static void sine_pin_low(void)
{
    GPIOC_BSRR = SINE_PIN_MASK << 16U;
}

static void sine_gpio_init(void)
{
    const uint32_t pin_shift = (SINE_PIN - 8UL) * 4UL;

    RCC_APB2ENR |= RCC_APB2ENR_IOPCEN;

    /* PC8: general purpose push-pull output, max speed 10 MHz. */
    GPIOC_CRH &= ~(0xFUL << pin_shift);
    GPIOC_CRH |= (0x1UL << pin_shift);

    sine_pin_low();
}

static void output_pwm_sample(uint32_t duty_percent)
{
    const uint32_t high_time_us = (PWM_PERIOD_US * duty_percent) / 100UL;
    const uint32_t low_time_us = PWM_PERIOD_US - high_time_us;

    if (high_time_us > 0U) {
        sine_pin_high();
        delay_us(high_time_us);
    }

    if (low_time_us > 0U) {
        sine_pin_low();
        delay_us(low_time_us);
    }
}

int main(void)
{
    const uint32_t sine_sample_count =
        sizeof(sine_duty_percent) / sizeof(sine_duty_percent[0]);

    cycle_counter_init();
    sine_gpio_init();

    while (1) {
        for (uint32_t sample = 0U; sample < sine_sample_count; sample++) {
            for (uint32_t i = 0U; i < SINE_HOLD_CYCLES; i++) {
                output_pwm_sample(sine_duty_percent[sample]);
            }
        }
    }
}
