/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_APB2ENR    (*(volatile uint32_t *)0x40021018U)
#define GPIOA_CRL      (*(volatile uint32_t *)0x40010800U)
#define GPIOA_BSRR     (*(volatile uint32_t *)0x40010810U)
#define GPIOC_CRH      (*(volatile uint32_t *)0x40011004U)
#define GPIOC_BSRR     (*(volatile uint32_t *)0x40011010U)

#define RCC_IOPAEN     (1U << 2)
#define RCC_IOPCEN     (1U << 4)

#define LED_PIN        5U      /* Nucleo-F103 on-board LD2: PA5 */
#define OUTPUT_PIN     8U      /* PC8 output */

static void delay(volatile uint32_t count)
{
    while (count-- != 0U)
    {
    }
}

int main(void)
{
    RCC_APB2ENR |= RCC_IOPAEN | RCC_IOPCEN;

    /* PA5: general-purpose push-pull output, 2 MHz. */
    GPIOA_CRL &= ~(0xFU << (LED_PIN * 4U));
    GPIOA_CRL |=  (0x2U << (LED_PIN * 4U));

    /* PC8: general-purpose push-pull output, 2 MHz. */
    GPIOC_CRH &= ~(0xFU << ((OUTPUT_PIN - 8U) * 4U));
    GPIOC_CRH |=  (0x2U << ((OUTPUT_PIN - 8U) * 4U));

    /* Loop forever */
	for(;;)
    {
        GPIOC_BSRR = (1U << OUTPUT_PIN);
        delay(500000U);
        GPIOC_BSRR = (1U << (OUTPUT_PIN + 16U));
        delay(500000U);
    }
}
