/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE        (0x40021000UL)
#define GPIOA_BASE      (0x40010800UL)
#define GPIOB_BASE      (0x40010C00UL)
#define ADC1_BASE       (0x40012400UL)

#define RCC_APB2ENR     (*(volatile uint32_t *)(RCC_BASE + 0x18UL))
#define RCC_CFGR        (*(volatile uint32_t *)(RCC_BASE + 0x04UL))

#define GPIOA_CRL       (*(volatile uint32_t *)(GPIOA_BASE + 0x00UL))
#define GPIOB_CRH       (*(volatile uint32_t *)(GPIOB_BASE + 0x04UL))
#define GPIOB_BSRR      (*(volatile uint32_t *)(GPIOB_BASE + 0x10UL))

#define ADC1_SR         (*(volatile uint32_t *)(ADC1_BASE + 0x00UL))
#define ADC1_CR2        (*(volatile uint32_t *)(ADC1_BASE + 0x08UL))
#define ADC1_SMPR2      (*(volatile uint32_t *)(ADC1_BASE + 0x10UL))
#define ADC1_SQR3       (*(volatile uint32_t *)(ADC1_BASE + 0x34UL))
#define ADC1_DR         (*(volatile uint32_t *)(ADC1_BASE + 0x4CUL))

#define RCC_APB2ENR_IOPAEN   (1UL << 2)
#define RCC_APB2ENR_IOPBEN   (1UL << 3)
#define RCC_APB2ENR_ADC1EN   (1UL << 9)

#define ADC_CR2_ADON         (1UL << 0)
#define ADC_CR2_CAL          (1UL << 2)
#define ADC_CR2_RSTCAL       (1UL << 3)
#define ADC_CR2_SWSTART      (1UL << 22)
#define ADC_SR_EOC           (1UL << 1)

#define ADC_MAX_COUNT        (4095UL)
#define VREF_MV              (3300UL)
#define CDS_LED_THRESHOLD    (2048UL)
#define LED_PB8_PIN          (8UL)

static volatile uint16_t cds_adc_raw;
static volatile uint32_t cds_voltage_mv;

static void delay_cycles(volatile uint32_t cycles)
{
    while (cycles-- != 0UL) {
        __asm volatile ("nop");
    }
}

static void adc1_pa0_init(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_ADC1EN;

    /* ADC clock must be <= 14 MHz. With 72 MHz PCLK2, ADCPRE /6 gives 12 MHz. */
    RCC_CFGR &= ~(3UL << 14);
    RCC_CFGR |= (2UL << 14);

    /* PA0(A0) analog input: MODE0 = 00, CNF0 = 00. */
    GPIOA_CRL &= ~(0xFUL << 0);

    /* ADC channel 0 sample time: 239.5 cycles, stable for high-impedance CDS dividers. */
    ADC1_SMPR2 &= ~(7UL << 0);
    ADC1_SMPR2 |= (7UL << 0);

    ADC1_SQR3 = 0UL; /* First regular conversion is channel 0. */

    ADC1_CR2 |= ADC_CR2_ADON;
    delay_cycles(1000UL);

    ADC1_CR2 |= ADC_CR2_RSTCAL;
    while ((ADC1_CR2 & ADC_CR2_RSTCAL) != 0UL) {
    }

    ADC1_CR2 |= ADC_CR2_CAL;
    while ((ADC1_CR2 & ADC_CR2_CAL) != 0UL) {
    }
}

static void led_pb8_init(void)
{
    RCC_APB2ENR |= RCC_APB2ENR_IOPBEN;

    /* PB8 output push-pull, max speed 2 MHz: MODE8 = 10, CNF8 = 00. */
    GPIOB_CRH &= ~(0xFUL << 0);
    GPIOB_CRH |= (2UL << 0);
}

static void led_pb8_set(uint8_t on)
{
    if (on != 0U) {
        GPIOB_BSRR = (1UL << LED_PB8_PIN);
    } else {
        GPIOB_BSRR = (1UL << (LED_PB8_PIN + 16UL));
    }
}

static uint16_t adc1_read_pa0(void)
{
    ADC1_CR2 |= ADC_CR2_SWSTART;
    while ((ADC1_SR & ADC_SR_EOC) == 0UL) {
    }

    return (uint16_t)(ADC1_DR & 0x0FFFUL);
}

int main(void)
{
    adc1_pa0_init();
    led_pb8_init();

    for (;;) {
        cds_adc_raw = adc1_read_pa0();
        cds_voltage_mv = ((uint32_t)cds_adc_raw * VREF_MV) / ADC_MAX_COUNT;
        led_pb8_set(cds_adc_raw < CDS_LED_THRESHOLD);
        delay_cycles(720000UL);
    }
}
