/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define SYSCLK_HZ                 8000000U
#define SERIAL_BAUDRATE           9600U

/* LED = PC8, Serial TX = USART2 PA2. */
#define LED_PIN                   8U
#define LED_ACTIVE_HIGH           1U

#define RCC_BASE                  0x40021000UL
#define AFIO_BASE                 0x40010000UL
#define GPIOA_BASE                0x40010800UL
#define GPIOC_BASE                0x40011000UL
#define TIM2_BASE                 0x40000000UL
#define USART2_BASE               0x40004400UL
#define NVIC_ISER_BASE            0xE000E100UL

#define RCC_APB2ENR_AFIOEN        (1U << 0)
#define RCC_APB2ENR_IOPAEN        (1U << 2)
#define RCC_APB2ENR_IOPCEN        (1U << 4)
#define RCC_APB1ENR_TIM2EN        (1U << 0)
#define RCC_APB1ENR_USART2EN      (1U << 17)

#define TIM_CR1_CEN               (1U << 0)
#define TIM_DIER_UIE              (1U << 0)
#define TIM_SR_UIF                (1U << 0)
#define TIM_EGR_UG                (1U << 0)

#define USART_SR_TXE              (1U << 7)
#define USART_CR1_TE              (1U << 3)
#define USART_CR1_TXEIE           (1U << 7)
#define USART_CR1_UE              (1U << 13)

#define TIM2_IRQn                 28U
#define USART2_IRQn               38U

typedef struct
{
    volatile uint32_t CR;
    volatile uint32_t CFGR;
    volatile uint32_t CIR;
    volatile uint32_t APB2RSTR;
    volatile uint32_t APB1RSTR;
    volatile uint32_t AHBENR;
    volatile uint32_t APB2ENR;
    volatile uint32_t APB1ENR;
    volatile uint32_t BDCR;
    volatile uint32_t CSR;
} RCC_TypeDef;

typedef struct
{
    volatile uint32_t EVCR;
    volatile uint32_t MAPR;
    volatile uint32_t EXTICR[4];
    volatile uint32_t MAPR2;
} AFIO_TypeDef;

typedef struct
{
    volatile uint32_t CRL;
    volatile uint32_t CRH;
    volatile uint32_t IDR;
    volatile uint32_t ODR;
    volatile uint32_t BSRR;
    volatile uint32_t BRR;
    volatile uint32_t LCKR;
} GPIO_TypeDef;

typedef struct
{
    volatile uint32_t CR1;
    volatile uint32_t CR2;
    volatile uint32_t SMCR;
    volatile uint32_t DIER;
    volatile uint32_t SR;
    volatile uint32_t EGR;
    volatile uint32_t CCMR1;
    volatile uint32_t CCMR2;
    volatile uint32_t CCER;
    volatile uint32_t CNT;
    volatile uint32_t PSC;
    volatile uint32_t ARR;
} TIM_TypeDef;

typedef struct
{
    volatile uint32_t SR;
    volatile uint32_t DR;
    volatile uint32_t BRR;
    volatile uint32_t CR1;
    volatile uint32_t CR2;
    volatile uint32_t CR3;
    volatile uint32_t GTPR;
} USART_TypeDef;

#define RCC                       ((RCC_TypeDef *)RCC_BASE)
#define AFIO                      ((AFIO_TypeDef *)AFIO_BASE)
#define GPIOA                     ((GPIO_TypeDef *)GPIOA_BASE)
#define GPIOC                     ((GPIO_TypeDef *)GPIOC_BASE)
#define TIM2                      ((TIM_TypeDef *)TIM2_BASE)
#define USART2                    ((USART_TypeDef *)USART2_BASE)
#define NVIC_ISER                 ((volatile uint32_t *)NVIC_ISER_BASE)

typedef enum
{
    UART_SEQUENCE_IDLE = 0,
    UART_SEQUENCE_WAIT_BYE,
    UART_SEQUENCE_DONE
} UartSequenceState;

static volatile uint32_t g_ms_ticks;
static volatile UartSequenceState g_uart_sequence_state;
static volatile uint32_t g_uart_bye_due_ms;

static const char *volatile g_uart_tx_data;
static volatile uint32_t g_uart_tx_len;
static volatile uint32_t g_uart_tx_pos;
static const char *volatile g_uart_pending_data;
static volatile uint32_t g_uart_pending_len;

void SystemInit(void);
void TIM2_IRQHandler(void);
void USART2_IRQHandler(void);

static void EnableIrq(void)
{
    __asm volatile ("cpsie i" ::: "memory");
}

static uint32_t SaveAndDisableIrq(void)
{
    uint32_t primask;

    __asm volatile ("mrs %0, primask" : "=r" (primask) :: "memory");
    __asm volatile ("cpsid i" ::: "memory");

    return primask;
}

static void RestoreIrq(uint32_t primask)
{
    if ((primask & 1U) == 0U)
    {
        __asm volatile ("cpsie i" ::: "memory");
    }
}

static void WaitForInterrupt(void)
{
    __asm volatile ("wfi");
}

static void NVIC_EnableIRQ(uint32_t irqn)
{
    NVIC_ISER[irqn / 32U] = (1UL << (irqn % 32U));
}

static uint32_t StringLength(const char *text)
{
    uint32_t length = 0U;

    while (text[length] != '\0')
    {
        length++;
    }

    return length;
}

static void LedOn(void)
{
#if LED_ACTIVE_HIGH
    GPIOC->BSRR = (1UL << LED_PIN);
#else
    GPIOC->BRR = (1UL << LED_PIN);
#endif
}

static void LedOff(void)
{
#if LED_ACTIVE_HIGH
    GPIOC->BRR = (1UL << LED_PIN);
#else
    GPIOC->BSRR = (1UL << LED_PIN);
#endif
}

static void UartStartTx(const char *data, uint32_t length)
{
    if (length == 0U)
    {
        return;
    }

    if (g_uart_tx_len != 0U)
    {
        g_uart_pending_data = data;
        g_uart_pending_len = length;
        return;
    }

    g_uart_tx_data = data;
    g_uart_tx_len = length;
    g_uart_tx_pos = 0U;
    USART2->CR1 |= USART_CR1_TXEIE;
}

static void UartWriteAsync(const char *text)
{
    uint32_t primask;

    primask = SaveAndDisableIrq();
    UartStartTx(text, StringLength(text));
    RestoreIrq(primask);
}

static void UartWriteAsyncFromIsr(const char *text)
{
    UartStartTx(text, StringLength(text));
}

static void StartSerialSequence(void)
{
    UartWriteAsync("HI\r\n");
    g_uart_bye_due_ms = g_ms_ticks + 3000U;
    g_uart_sequence_state = UART_SEQUENCE_WAIT_BYE;
}

static void DelayMs(uint32_t delay_ms)
{
    const uint32_t start_ms = g_ms_ticks;

    while ((uint32_t)(g_ms_ticks - start_ms) < delay_ms)
    {
        WaitForInterrupt();
    }
}

static void GPIO_Init(void)
{
    RCC->APB2ENR |= RCC_APB2ENR_AFIOEN | RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPCEN;

    (void)AFIO->MAPR;

    /* PA2: USART2_TX, alternate function push-pull, 2 MHz. */
    GPIOA->CRL &= ~(0xFUL << (2U * 4U));
    GPIOA->CRL |= (0xAUL << (2U * 4U));

    /* PA3: USART2_RX, floating input. */
    GPIOA->CRL &= ~(0xFUL << (3U * 4U));
    GPIOA->CRL |= (0x4UL << (3U * 4U));

    /* PC8: LED output, push-pull, 2 MHz. */
    GPIOC->CRH &= ~(0xFUL << ((LED_PIN - 8U) * 4U));
    GPIOC->CRH |= (0x2UL << ((LED_PIN - 8U) * 4U));

    LedOff();
}

static void USART2_Init(void)
{
    RCC->APB1ENR |= RCC_APB1ENR_USART2EN;

    USART2->CR1 = 0U;
    USART2->BRR = (SYSCLK_HZ + (SERIAL_BAUDRATE / 2U)) / SERIAL_BAUDRATE;
    USART2->CR1 = USART_CR1_TE | USART_CR1_UE;

    NVIC_EnableIRQ(USART2_IRQn);
}

static void TIM2_Init(void)
{
    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;

    TIM2->CR1 = 0U;
    TIM2->PSC = 8U - 1U;
    TIM2->ARR = 1000U - 1U;
    TIM2->EGR = TIM_EGR_UG;
    TIM2->SR = 0U;
    TIM2->DIER = TIM_DIER_UIE;

    NVIC_EnableIRQ(TIM2_IRQn);
    TIM2->CR1 = TIM_CR1_CEN;
}

static void HardwareInit(void)
{
    GPIO_Init();
    USART2_Init();
    TIM2_Init();
    EnableIrq();
}

void SystemInit(void)
{
}

int main(void)
{
    HardwareInit();

    for (;;)
    {
        LedOn();
        DelayMs(1000U);

        StartSerialSequence();
        DelayMs(2000U);

        LedOff();
        DelayMs(1000U);
    }
}

void TIM2_IRQHandler(void)
{
    if ((TIM2->SR & TIM_SR_UIF) != 0U)
    {
        TIM2->SR &= ~TIM_SR_UIF;
        g_ms_ticks++;

        if ((g_uart_sequence_state == UART_SEQUENCE_WAIT_BYE) &&
            ((int32_t)(g_ms_ticks - g_uart_bye_due_ms) >= 0))
        {
            UartWriteAsyncFromIsr("Bye\r\n");
            g_uart_sequence_state = UART_SEQUENCE_DONE;
        }
    }
}

void USART2_IRQHandler(void)
{
    if (((USART2->CR1 & USART_CR1_TXEIE) != 0U) &&
        ((USART2->SR & USART_SR_TXE) != 0U))
    {
        if (g_uart_tx_pos < g_uart_tx_len)
        {
            USART2->DR = (uint32_t)(uint8_t)g_uart_tx_data[g_uart_tx_pos];
            g_uart_tx_pos++;
        }
        else
        {
            USART2->CR1 &= ~USART_CR1_TXEIE;
            g_uart_tx_data = 0;
            g_uart_tx_len = 0U;
            g_uart_tx_pos = 0U;

            if (g_uart_pending_len != 0U)
            {
                const char *pending_data = g_uart_pending_data;
                const uint32_t pending_len = g_uart_pending_len;

                g_uart_pending_data = 0;
                g_uart_pending_len = 0U;
                UartStartTx(pending_data, pending_len);
            }
        }
    }
}
